-- Шаблоны Telegram-уведомлений о конкретных вебинарах.
-- webinar_id хранится text, как и в webinar_reminder_sends: это не зависит от текущего типа ID таблицы webinars.
-- offset_minutes_before позволяет создавать уведомления на любое число минут до начала.

create table if not exists public.webinar_notification_templates (
  id bigint generated by default as identity primary key,
  webinar_id text not null,
  reminder_type text not null check (
    reminder_type in ('3_days', '1_day', '6_hours', '15_minutes')
    or reminder_type ~ '^custom_[1-9][0-9]*_minutes$'
  ),
  offset_minutes_before integer not null check (offset_minutes_before > 0),
  message_text text not null default '',
  file_id text null,
  file_type text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint webinar_notification_templates_unique
    unique (webinar_id, reminder_type),
  constraint webinar_notification_templates_unique_offset
    unique (webinar_id, offset_minutes_before)
);

create index if not exists webinar_notification_templates_webinar_idx
  on public.webinar_notification_templates (webinar_id);

create or replace function public.set_webinar_notification_template_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists webinar_notification_templates_set_updated_at
  on public.webinar_notification_templates;

create trigger webinar_notification_templates_set_updated_at
before update on public.webinar_notification_templates
for each row
execute function public.set_webinar_notification_template_updated_at();

alter table public.webinar_notification_templates enable row level security;

-- Шаблоны читает и изменяет только серверный webhook / cron через service_role.
revoke all on table public.webinar_notification_templates from anon, authenticated;
revoke all on sequence public.webinar_notification_templates_id_seq from anon, authenticated;

-- Начальные шаблоны добавляются всем уже существующим вебинарам, но не перезаписывают
-- сохранённые администратором тексты и файлы.
insert into public.webinar_notification_templates (
  webinar_id,
  reminder_type,
  offset_minutes_before,
  message_text
)
select
  webinar.id::text,
  template.reminder_type,
  template.offset_minutes_before,
  template.message_text
from public.webinars as webinar
cross join (
  values
    (
      '3_days',
      4320,
      $$⚠️ ВНИМАНИЕ ВСЕМ СЕКТОРАМ!

Проверка систем жизнеобеспечения завершена. До нашего большого бесплатного онлайн-интенсива осталось ровно 3 дня! 🚀

Мы покажем тебе, как устроен District изнутри, и разберём реальные ловушки ЦТ из части Б, на которых теряют баллы даже сильные школьники. 🎯

Готовься. Арена уже близко. 🔥$$
    ),
    (
      '1_day',
      1440,
      $$🎒 СПОНСОРСКИЙ ПАРАШЮТ ДЛЯ ВЕБА!

До старта осталось 24 часа.

Завтра в {{webinar_time}} Арена District официально активируется. ⚡️

Чтобы ты пришёл на трансляцию заряженным, наши менторы приготовили для тебя микро-гайд:

📕 «Формулы тригонометрии, которые спасут тебя на ЦТ»

Забирай гайд уже сегодня и просмотри его до начала вебинара. 📚

А завтра мы покажем, как эти формулы работают в реальном бою и где именно школьники чаще всего попадаются на ловушки ЦТ. 🎯

До встречи на Арене. Завтра в {{webinar_time}}! 🔥$$
    ),
    (
      '6_hours',
      360,
      $$⚡️ ДЕНЬ ИКС НАСТАЛ, ТРИБУТ!

Сбор фракции объявлен. Сегодня в {{webinar_time}} мы выходим на Арену District. 🏟️

Готовь тетрадку, ручку и чай ☕️ — Лидия Владимировна проведёт разбор ловушек ЦТ, после которого ты начнёшь щёлкать тригонометрию как орехи. 🧠🔥

⏱ Таймер запущен.

Ровно через 6 часов в этом чате откроется прямой телепорт на вебинар.

Будь на связи. 🚀$$
    ),
    (
      '15_minutes',
      15,
      $$⚡️ ТЕЛЕПОРТ АКТИВИРОВАН

Лидия Владимировна уже в эфире, а менторы заняли свои позиции в чате поддержки. 🧑‍🏫🔥

Мы начинаем взлом ЦТ прямо сейчас.

Залетай на Арену по кнопке ниже, пока система не ограничила доступ! 👇

🎯 Твои 80+ баллов начинаются здесь.$$ 
    )
) as template(reminder_type, offset_minutes_before, message_text)
on conflict (webinar_id, offset_minutes_before) do nothing;
