-- Журнал отправленных Telegram-напоминаний о вебинарах.
-- webinar_id хранится текстом, чтобы миграция не зависела от текущего типа id
-- в существующей таблице public.webinars. В приложении используется String(webinar.id).

create table if not exists public.webinar_reminder_sends (
  id bigint generated by default as identity primary key,
  webinar_id text not null,
  telegram_id bigint not null,
  reminder_type text not null check (
    reminder_type in ('3_days', '1_day', '6_hours', '15_minutes')
    or reminder_type ~ '^custom_[1-9][0-9]*_minutes$'
  ),
  sent_at timestamp with time zone not null default now(),
  constraint webinar_reminder_sends_unique
    unique (webinar_id, telegram_id, reminder_type)
);

create index if not exists webinar_reminder_sends_webinar_type_idx
  on public.webinar_reminder_sends (webinar_id, reminder_type);

alter table public.webinar_reminder_sends enable row level security;

-- Не выдаём публичный доступ: обработчик cron использует только service_role.
revoke all on table public.webinar_reminder_sends from anon, authenticated;
revoke all on sequence public.webinar_reminder_sends_id_seq from anon, authenticated;
